# Servidor
server.port=${PORT:8080}

# Conexion a MySQL
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/pizzeria_la_esquina?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=false

# Nombre de la aplicacion
app.nombre=Pizzeria La Esquina